### ISSUE TITLE
Dataset 

### ISSUE THREAD

**Issue by shnhrtkyk** [lehmannfa/HEMEW3D#1]
I attempted to download the dataset from [this link](https://entrepot.recherche.data.gouv.fr/dataset.xhtml?persistentId=doi:10.57745/LAI6YU), but the download process is taking an exceptionally long time. Would it be possible to provide an alternative download site?

**Comment by lehmannfa** [comment]
Hello, Thank you for reaching out and my apologies for the delay in my response. Were you able to download the data? Due to the size of the database, it is not available on another repository but I can ask the support for advice if you are experimenting issues.
